language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
    - php vendor/bin/phpunit
