language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.2

before_install:
    - travis_retry composer self-update

install:
    - if [[ $setup != 'lowest' ]]; then travis_retry composer install --no-interaction --no-suggest --prefer-dist; fi
    - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable; fi

script:
    - php vendor/bin/phpunit
